version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - price-feed-service
      - user-auth-service

  price-feed-service:
    build:
      context: ./backend/price-feed-service
      dockerfile: Dockerfile
    ports:
      - "3100:3000"
    environment:
      - NODE_ENV=production
      # 開發環境
      # - NODE_ENV=development
    depends_on:
      - redis
      - rabbitmq

  user-auth-service:
    build:
      context: ./backend/user-auth-service
      dockerfile: Dockerfile
    ports:
      - "3200:3000"
    environment:
      - NODE_ENV=production
      # 開發環境
      # - NODE_ENV=development
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"